update scripts/pomo

diff --git a/scripts/pomo b/scripts/pomo
--- a/scripts/pomo
+++ b/scripts/pomo
@@ -7,36 +7,36 @@ duration="1500"
 remains=
 
 duration_parse() {
-    dur="$1"
-    h=0 m=0 s=0
+	dur="$1"
+	h=0 m=0 s=0
 
-    if ! [[ $dur =~ h|m|s ]]; then
-        printf 'missing unit in duration "%d"\n' "$dur" 1>&2
-        exit 1
-    fi
+	if ! [[ $dur =~ h|m|s ]]; then
+		printf 'missing unit in duration "%d"\n' "$dur" 1>&2
+		exit 1
+	fi
 
-    # calclulate in positive. the negative sign will be added back at
-    # the end of the function
-    [[ ${1:0:1} == '-' ]] && dur="${dur#-}"
+	# calclulate in positive. the negative sign will be added back at
+	# the end of the function
+	[[ ${1:0:1} == '-' ]] && dur="${dur#-}"
 
-    if [[ $dur =~ [0-9]*h ]]; then
-        h="${dur%%h*}"
-        dur="${dur##*h}"
-    fi
+	if [[ $dur =~ [0-9]*h ]]; then
+		h="${dur%%h*}"
+		dur="${dur##*h}"
+	fi
 
-    if [[ $dur =~ [0-9]*m ]]; then
-        m="${dur%%m*}"
-        dur="${dur##*m}"
-    fi
+	if [[ $dur =~ [0-9]*m ]]; then
+		m="${dur%%m*}"
+		dur="${dur##*m}"
+	fi
 
-    if [[ $dur =~ [0-9]*s ]]; then
-        s="${dur%%s*}"
-        dur="${dur##*s}"
-    fi
+	if [[ $dur =~ [0-9]*s ]]; then
+		s="${dur%%s*}"
+		dur="${dur##*s}"
+	fi
 
-    ((duration = h * 3600 + m * 60 + s))
+	((duration = h * 3600 + m * 60 + s))
 
-    [[ ${1:0:1} == '-' ]] && ((duration *= -1))
+	[[ ${1:0:1} == '-' ]] && ((duration *= -1))
 }
 
 # report whether a timer is running
@@ -49,47 +49,50 @@ timer_remains() {
 	local start duration end now
 	remains=
 
-    read start duration < "/tmp/pomo"
-    ((end = start + duration))
-    printf -v now "%(%s)T"
-    ((remains = end - now))
+	read start duration <"/tmp/pomo"
+	((end = start + duration))
+	printf -v now "%(%s)T"
+	((remains = end - now))
 }
 
 # pretty print the timer
 timer_print() {
-    local p=$prefix_work
-    local sign=''
+	local p=$prefix_work
+	local sign=''
 
 	((remains == 0)) && p=$prefix_stop
 	((remains < 0)) && p=$prefix_break
 
 	((remains < 0)) && {
-        local sign='-'
-        ((remains *= -1))
-        ((remains % 2 != 0)) && p=''   # blinking effect
+		local sign='-'
+		((remains *= -1))
+		((remains % 2 != 0)) && p=' ' # blinking effect
 	}
 
-    #((hours   = remains / 3600, remains %= 3600))
-    ((minutes = remains / 60,   remains %= 60))
+	#((hours   = remains / 3600, remains %= 3600))
+	((minutes = remains / 60, remains %= 60))
 
-    printf -v l '%02d:%02d' $minutes $remains
-    [[ -n $sign ]] && l="$sign$l"
+	printf -v l '%02d:%02d' $minutes $remains
+	[[ -n $sign ]] && l="$sign$l"
 	l="$p $l"
 
-	echo "$l"
+	test -t 0 &&
+		printf '%s\r' "$l" ||
+		printf '%s\n' "$l"
 }
 
 # print the current timer
 print() {
-    timer_running || {
+	timer_running || {
 		remains=0
 		timer_print
-        return
+		return
 	}
 
 	timer_remains
 	timer_print
-}; cmds="$cmds print"
+}
+cmds="$cmds print"
 
 # start a new timer
 start() {
@@ -97,22 +100,28 @@ start() {
 
 	[[ -n $d ]] && duration_parse "$d"
 	# -1 represents the current time. read bash(1).
-	printf '%(%s)T %d\n' -1 "$duration" > "/tmp/pomo"
-}; cmds="$cmds start"
+	printf '%(%s)T %d\n' -1 "$duration" >"/tmp/pomo"
+}
+cmds="$cmds start"
 
 # stop the timer
 stop() {
 	rm "/tmp/pomo" 2>/dev/null
-}; cmds="$cmds stop"
+}
+cmds="$cmds stop"
 
 # keep printing the timer to stdout
 follow() {
-	enable sleep	# enable built-in sleep
+	enable sleep # enable built-in sleep
+	tput civis
+	trap 'tput cnorm' EXIT
+	clear
 	while :; do
 		print
 		sleep 1
 	done
-}; cmds="$cmds follow"
+}
+cmds="$cmds follow"
 
 main() {
 	local cmd="$1"
